export const COLLABORATOR_REPOSITORY = 'COLLABORATOR_REPOSITORY';
export const DOCUMENT_TYPE_REPOSITORY = 'DOCUMENT_TYPE_REPOSITORY';
export const COLLABORATOR_DOCUMENT_TYPE_REPOSITORY =
  'COLLABORATOR_DOCUMENT_TYPE_REPOSITORY';
export const DOCUMENT_REPOSITORY = 'DOCUMENT_REPOSITORY';
export const STATISTICS_REPOSITORY = 'STATISTICS_REPOSITORY';
